### ISSUE TITLE
Connecting Linux Tests from Core to Distributable Linux

### ISSUE THREAD

**Issue by shaggyyy2002** [metacall/distributable-linux#18]
On the Core Repo, We have used repository dispatch action, so that when a tag is pushed, it will check the tests and if passed it will trigger this repo's CI to build the distributable for Linux. 
Solution continues for this issue ->  Core Repo : https://github.com/metacall/core/issues/505

```yml
name: "MetaCall Distributable Linux Release"

on:
  repository_dispatch:
    types: [test-trigger]
  pull_request:
  push:
    tags:
      - 'v*.*.*'
```
